{% set name = "jobrunner" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e54decb9c26a0c74ea78a2a7e0e25a82925e2752d385c66ef0fdb1abf8ac0199

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - pytest-runner
  run:
    - psutil
    - python
    - qarrayrun

test:
  imports:
    - jobrunner

about:
  home: https://github.com/CFSAN-Biostatistics/jobrunner
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: An abstraction layer to run jobs on HPC clusters using Grid Engine, Torque, or locally.

extra:
  recipe-maintainers:
    - dpryan79
