{% set name = "jobrunner" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 73f406901c6e25bd12c166a5fcb13590a4f424664526d554e82462fedd3e0c4b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - pytest-runner
  run:
    - psutil
    - python
    - qarrayrun

test:
  imports:
    - jobrunner

about:
  home: https://github.com/CFSAN-Biostatistics/jobrunner
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: An abstraction layer to run jobs on HPC clusters using Grid Engine, Torque, or locally.

extra:
  recipe-maintainers:
    - dpryan79
