travis:
  secure:
    BINSTAR_TOKEN: P8HOkcuvVKfpJJ5mG8jNrcFDKA9DxhvMcFf6vDbuqZIhP2IKcZw2PPCwbir88DNir4c32gQbLbdlohx0dhZSRNznf4O0yxy24yvp+eBGwaHemWXXdg0b60f5Z2L2fEqxF6pVxpz8dB4stevfkgVKZyDmN7lP+RRxqf40sV6Vc9lS9GoMsSfuuIP1pmaB7F8jJnzFMTgLBXrhh/c7L4uGuk4ItDmv7tYs3HTcaiPEtZ/otZFEhnNDv2UK7E2Q3LQa4kJHKuyr8qaZzM+FkLHGTjHXsFf+zb/JsNDciV6TxSN4/RDtLyn2L5XFxmTNVnIuVj5Lacc3JM4z8Ql7wiVkRHh9JJYLvyniEuSKy3hMagTmCXj2Kn8sa8MvAqYS8ScN16TUCCfJ4k0nh1c2pwWQidjUYMSL4zNQCX7pNjREVxLUYpOaPvFpXlR8B6ZGMW5ZOMDXGOVH9KoZsgGBozbEbk9aIc0c4t3MtV19lte1Q843E4FvicIZOSiO6XJQ2tBi00Vd0A89tou9mYnOCw9EvtYZtjnACPqvq0Wnz4pYcrQNwXg2DIHuT5xX6OImjwWR6OgrtFqZZ7j1re+8D7O2o3cI7oH5vU9DP8rh3wgGoNpMulb+WwMiUTgChpO1R4DQsrZ+WyMkMV+xeCwyXXSfqX+5U+vE7HRlihTgOsmpDkQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
